---
all:
  children:
    leader:
      hosts:
        kube-master.toudherebarry.com:
    # followers:
    #   hosts:
    #     ...
    workers:
      hosts:
        kube-node.toudherebarry.com:
    proxy:
      hosts:
        ha-proxy.toudherebarry.com:
    masters:
      children:
        leader:
        # followers:
    kubernetes:
      children:
        masters:
        workers:
      
