---
- name: Update and upgrade apt
  apt:
    upgrade: yes
    update_cache: yes

- name: Intall ha-proxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Send proxy configuration
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: 
    - Restart haproxy
