---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Uninstall existing docker
  apt:
    name: ['docker.io', 'docker-ce', 'docker-ce-cli', 'containerd']
    state: absent
    update_cache: yes

- name: Update and upgrade apt
  apt:
    upgrade: yes
    update_cache: yes

- name: Install needed packages
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'software-properties-common', 'curl', 'wget']
    state: present
    update_cache: yes

- name: Install docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Apt key for kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubernetes repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Update for kube install
  shell: |
    apt-get update

- name: Install kubernetes binaries
  apt:
    name: ['kubeadm', 'kubelet', 'kubectl']
    state: present
    update_cache: yes

- name: Hold kubernetes version
  shell: |
    apt-mark hold kubelet kubeadm kubectl



